a=int(input("집의 크기를 입력하세요"))
import turtle
t=turtle.Turtle()
t.setheading(180)
t.forward(a)
t.setheading(60)
t.forward(a)
t.right(120)
t.forward(a)
t.right(30)
t.forward(a)
t.right(90)
t.forward(a)
t.right(90)
t.forward(a)
turtle.done()