import turtle
from random import*
score=0
n=randint(5,10)
fruit=['apple','banana','strawberry','watermelon','mandarin','peach','grapes','orange','pear','kiwi']
t=turtle.Turtle('turtle')
t.speed(0)
t.setx(-200)
t.write('0')
t.setx(0)
t.write('50')
t.setx(200)
t.write('100')
t.begin_fill()
t.fillcolor('yellow')
t.setx(320)
t.right(90)
t.sety(100)
t.setx(220)
t.sety(0)
t.end_fill()
t.backward(100)
t.begin_fill()
t.fillcolor('red')
t.goto(270,200)
t.goto(320,100)
t.end_fill()
t.penup()
t.goto(20,200)
t.left(90)
t.write('김주환의 타자 게임!', font=('Arial',20,'bold'))
t.goto(0,250)
for i in range(n):
    s=choice(fruit)
    word=turtle.textinput('fruit','%s(%d/%d)'%(s,i+1,n))
    if word==s:
        score+=1
rate=score/n*100
t.penup()
t.goto(0,-50)
t.pendown()
t.write('%d/%d번 성공!'%(score,n),True,font=('Arial',15,'bold'))
t.penup()
t.goto(0,-100)
t.pendown()
t.write('정확도:%.1f%%'%(rate),True,font=('Arial',15,'bold'))
t.penup()
t.goto(-200,10)
t.pendown()
t.pencolor('skyblue')
t.pensize(10)
t.forward(400/100*rate)
turtle.done()